# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 12:36
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockCode', models.CharField(max_length=30)),
                ('CompanyName', models.CharField(max_length=100)),
                ('Industry', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StockEarnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectedEarning', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('LastQuarterEarning', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('LastYearEarning', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('BeatorMissThisQuater', models.BooleanField()),
                ('PositivOrNagetiv', models.BooleanField()),
                ('StockCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TopPositivEarning2day.StockCode')),
            ],
        ),
    ]
