# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopPositivEarning2day', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockearnings',
            name='EntryName',
            field=models.CharField(default='Test', max_length=30),
        ),
    ]
